### ISSUE TITLE
Create a screen-responsive loader component

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/FoGit#22]
**Please describe the motive behind this issue.**
- Need a loader to indicate the loading state.

**Describe the solution you'd like to propose**
- The loader must be screen responsive
- Must be customizable in terms of styles

**Describe alternatives you've considered**
- NA

**Additional context**
- For inspiration/reference https://www.sliderrevolution.com/resources/css-loaders/

**Comment by selamanse** [comment]
@DemonDaddy22 I will try this, can you assign me please?

**Comment by DemonDaddy22** [comment]
@selamanse Sure you can take this up!
Just create a responsive and customisable loader, I will integrate it later wherever the loading state needs to displayed.
Also, please share screenshot(s), so that if something needs to be tweaked, I can suggest that before merging your PR.
