### ISSUE TITLE
Add test suite for createListOfSize util

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/FoGit#29]
**Please describe the motive behind this issue.**
Need a new test suite for createListOfSize util method.

**Describe the solution you'd like to propose**
Create a new test suite containing relevant test cases to test the createListOfSize util.

**Describe alternatives you've considered**
NA

**Additional context**
Update the util in case any edge case is not covered by the current implementation.

**Comment by selamanse** [comment]
@DemonDaddy22 I'd like to try this can you assign me please?

**Comment by DemonDaddy22** [comment]
@selamanse Yes sure, you can go ahead and create a PR for same!
