### ISSUE TITLE
Setup a build workflow to automatically build and deploy the website on GH Pages

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/FoGit#31]
**Please describe the motive behind this issue.**
- Need to take the project on production environment so that it can be tried out on different screens.

**Describe the solution you'd like to propose**
- Add GH Pages to project
- Setup a workflow to deploy the application whenever changes are pushed to master branch.

**Describe alternatives you've considered**
- Manually deploying the application everytime which would be time-consuming and inconvenient.

**Additional context**
NA

**Comment by selamanse** [comment]
I can take care of this @DemonDaddy22, can you assign me?

**Comment by DemonDaddy22** [comment]
@selamanse I will complete this, as it will be easier for me to verify and test the correctness of the workflow. You can take up either #19 or #22 for now.
