### ISSUE TITLE
Prevent generation of source map when app is deployed

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/FoGit#4]
**Please describe the motive behind this issue.**
Current implementation will not prevent anyone from viewing the source map of the deployed app

**Describe the solution you'd like to propose**
Somehow prevent the end-user to view the source map of the deployed website

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ankitgauri26** [comment]
@DemonDaddy22 - Currently how are you creating the build? If you want to write Docker file to create an image of your project without generating the sourcemap, i can do that? I can write docker file of your application if required.

**Comment by ankitgauri26** [comment]
@DemonDaddy22 - Please assign this issue to me. I can disable the generation of source maps when we build the application.

**Comment by ankitgauri26** [comment]
@DemonDaddy22  - I have done the changes and raised the PR.

Initial State (before the PR), sourcemaps gets generated when we build the application
![image](https://user-images.githubusercontent.com/22481268/135722090-0f95bf3d-93d6-43c5-8778-b415b2694f26.png)

Updated State (Raised PR), sourcemaps are not generated when we build the application.
![image](https://user-images.githubusercontent.com/22481268/135722104-b6ec594d-62e2-4265-a408-5f5b7ce9a985.png)

**Comment by ankitgauri26** [comment]
@DemonDaddy22  - Thank you for assigning the issue. 
I have already created PR for the same.

Thanks again for giving me the opportunity to work on this item

**Comment by DemonDaddy22** [comment]
Hey @ankitgauri26, although I won't be using Docker, I'm planning to simply build the project in the default manner and use Vercel to deploy the application. This whole process will be automated using GitHub Actions soon.
But I would love to know how you were planning to do it using Docker.

**Comment by DemonDaddy22** [comment]
Also, @ankitgauri26 can you please follow the PULL_REQUEST_TEMPLATE to create your PR. That would make my life easier and enable me to merge your changes quicker! 🙂

**Comment by ankitgauri26** [comment]
@DemonDaddy22  - Sure. I'll use that.
I am totally new and haven't done PULL_REQUEST_TEMPLATE. Can you help me how I can do that? I have checked the main branch and found the template but how can i update it and where i can update the information. Thanks in advance.
