### ISSUE TITLE
Update app icon for browser title bar

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/FoGit#9]
**Please describe the motive behind this issue.**
Current icon is the default React icon

**Describe the solution you'd like to propose**
Need a new icon (related to GitHub) for browser title bar

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ankitgauri26** [comment]
@DemonDaddy22  - Do we have any icon to replace it with current React icon or do we need to create a new icon?

**Comment by shobhit-bhatt-14** [comment]
@DemonDaddy22  You just need to place the desired favicon(title bar icon) in the public folder and specify its reference in the head tag of html file in the public folder.

**Comment by DemonDaddy22** [comment]
@ankitgauri26 Not really, I wanted someone to add an icon related to GitHub or related to people, which would be aligned to the website's theme. If you find something related to this, you can share the link(s) to the same, and then we can shortlist one of them.

**Comment by DemonDaddy22** [comment]
@shobhit-bhatt-14 Yes Shobhit that's correct. But I want someone else to do this, in order to get started with open-source contributions. This is a pretty easy task, will soon be adding decent level issues too.

**Comment by ankitgauri26** [comment]
@DemonDaddy22  - Please assign this issue to me. I'll search and give you the links and work on this issue

**Comment by ankitgauri26** [comment]
@DemonDaddy22  - I can work it on sat/sun because of tight office schedule. Apologies for the delay. If anyone can work on it before sat/sun, you can reassign to him/her else I can work on this weekend.
Again apologies for the delay

**Comment by DemonDaddy22** [comment]
@ankitgauri26 No worries mate! I just thought you didn't revert back so maybe you didn't want to do it! I am myself busy with the office work for the major part of the day so I can totally understand. Thanks for the update!

**Comment by DemonDaddy22** [comment]
@ankitgauri26 something like this? https://iconmonstr.com/user-13-svg/
Want an icon that relates to people or to Git/GitHub.
